server:
  port: 8282  servlet:    context-path: /MyPhonebook
spring:  datasource:    username: phnbk_local
    password: local
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name:   oracle.jdbc.driver.OracleDriver  mvc:    view:      prefix: /views/
      suffix: .jsp     jpa:
   properties:      hibernate:
       show_sql:true
       format_sql:true
   hibernate:      ddl-auto: update            